ENH: add support for the Syllable OS (http://www.syllable.org) major issues: -access() doesn't return false for an empty string (#ifdefed in cmake) -dlopen() doesn't return 0 on failure (#ifdefed in cmake and fixed now in Syllable) -the kwsys and Bootstrap tests fail with timeout due to the fact that I'm doing all that in qemu, which is quite slow -RPATH is now supported, so without modifying the test adapting DLL_PATH in Syllable is required for the tests to succeed -the Plugin test fails with an undefined reference to example_exe_function() in example_mod_1, it seems this isn't supported under Syllable
Alex